### ISSUE TITLE
How to start GUI?

### ISSUE THREAD

**Issue by christopherisnow** [Sology/maily_herald#48]
Just installed MH for a test spin. How do I run it/set it up? 

```
$ maily_herald 
uninitialized constant #<Class:MailyHerald>::Pathname
/var/lib/gems/2.5.0/gems/maily_herald-0.9.4/lib/maily_herald.rb:387:in `read_options'
/var/lib/gems/2.5.0/gems/maily_herald-0.9.4/lib/maily_herald/cli.rb:99:in `setup_options'
/var/lib/gems/2.5.0/gems/maily_herald-0.9.4/lib/maily_herald/cli.rb:15:in `parse'
/var/lib/gems/2.5.0/gems/maily_herald-0.9.4/bin/maily_herald:9:in `<top (required)>'
/usr/local/bin/maily_herald:23:in `load'
/usr/local/bin/maily_herald:23:in `<main>'
```

Sorry, not a Ruby on Rails user... is the software too young for general users?

**Comment by ssoulless** [comment]
Well, it is not actively maintained, it should not be used for production Imao.
