### ISSUE TITLE
uninitialized constant MailyHerald::Webui::Breadcrumbs

### ISSUE THREAD

**Issue by c4lliope** [Sology/maily_herald#50]
![Screen Shot 2021-12-06 at 12 17 49 PM](https://user-images.githubusercontent.com/30454698/144891624-88eb6427-fd4d-4a9a-aaa5-2f36e342fcf3.png)

```
ruby 2.7.4
rails 6.0.0

    maily_herald (0.9.4)
      liquid (> 2.6.1)
      rails (> 3.2)
      sidekiq
    maily_herald-webui (0.9.0)
      coffee-rails
      haml
      maily_herald (~> 0.9.2)
      sass-rails
      smart_listing (~> 1.1.0)
```

Stack trace:
```
maily_herald-webui (0.9.0) app/controllers/maily_herald/webui/application_controller.rb:4:in `<class:ApplicationController>'
maily_herald-webui (0.9.0) app/controllers/maily_herald/webui/application_controller.rb:3:in `<module:Webui>'
maily_herald-webui (0.9.0) app/controllers/maily_herald/webui/application_controller.rb:2:in `<module:MailyHerald>'
maily_herald-webui (0.9.0) app/controllers/maily_herald/webui/application_controller.rb:1:in `<main>'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
skylight-core (4.3.0) lib/skylight/core/probes.rb:118:in `require'
zeitwerk (2.3.0) lib/zeitwerk/kernel.rb:16:in `require'
maily_herald-webui (0.9.0) app/controllers/maily_herald/webui/dashboard_controller.rb:2:in `<module:MailyHerald>'
maily_herald-webui (0.9.0) app/controllers/maily_herald/webui/dashboard_controller.rb:1:in `<main>'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
bootsnap (1.4.6) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
skylight-core (4.3.0) lib/skylight/core/probes.rb:118:in `require'
zeitwerk (2.3.0) lib/zeitwerk/kernel.rb:16:in `require'
activesupport (6.0.2.2) lib/active_support/inflector/methods.rb:284:in `const_get'
activesupport (6.0.2.2) lib/active_support/inflector/methods.rb:284:in `block in constantize'
activesupport (6.0.2.2) lib/active_support/inflector/methods.rb:280:in `each'
activesupport (6.0.2.2) lib/active_support/inflector/methods.rb:280:in `inject'
activesupport (6.0.2.2) lib/active_support/inflector/methods.rb:280:in `constantize'
activesupport (6.0.2.2) lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
actionpack (6.0.2.2) lib/action_dispatch/http/request.rb:88:in `controller_class_for'
actionpack (6.0.2.2) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:45:in `controller'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
skylight-core (4.3.0) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
skylight-core (4.3.0) lib/skylight/core/fanout.rb:25:in `instrument'
skylight-core (4.3.0) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
railties (6.0.2.2) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.2.2) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
skylight-core (4.3.0) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
skylight-core (4.3.0) lib/skylight/core/fanout.rb:25:in `instrument'
skylight-core (4.3.0) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
skylight-core (4.3.0) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
honeybadger (4.6.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.6.0) lib/honeybadger/agent.rb:399:in `with_rack_env'
honeybadger (4.6.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (4.6.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (4.6.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
rack (2.2.2) lib/rack/handler/webrick.rb:95:in `service'
/Users/grace/.rbenv/versions/2.7.4/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/Users/grace/.rbenv/versions/2.7.4/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/Users/grace/.rbenv/versions/2.7.4/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread' 
```

**Comment by c4lliope** [comment]
Seems like an issue here: https://github.com/Sology/maily_herald-webui/blob/master/app/controllers/maily_herald/webui/application_controller.rb#L4

I can close/reopen this issue on the `maily_herald-webui` codebase if needed.
